### ISSUE TITLE
[enhancement] Possibility to define the Tooltip Width

### ISSUE THREAD

**Issue by 5axes** [Ghostkeeper/SettingsGuide#15]
Would be great to have the possibility to define the tooltip width in case of using the setting 'Show articles in setting tooltip'. If the help is a very long article not all the complete text is visible in the help. Enlarge the tooltip windows will ensure the possibility to visualize the complete help article !
![help](https://user-images.githubusercontent.com/11015345/74416615-b08d9480-4e45-11ea-84b1-403f178fb156.jpg)

**Comment by Ghostkeeper** [comment]
Yeah I had this implemented actually. However it turned out that this only worked in my source build of Cura (which uses a newer version of Qt). In the official builds of Cura, it wouldn't let me browse the element tree of the GUI so the code didn't find any tooltip to increase the width of.

I've since made a different implementation that adds a new theme to your configuration folder, which has the tooltip width adjusted. It copies your current theme. It's completely transparent to the user except that the name of the active theme in the preferences screen gets duplicated. But it works! This makes it possible to actually read the entire article in just the tooltip, in most cases (depending on your screen size too).

I'm not going to enable this by default yet. I'd first like to get a release out to see what people think and if any bugs come up. However the most common criticism I get with this plug-in is that it's really hard to discover where the guide is, and this is going to be my solution to that.

So, yes, this is fixed in the upcoming 2.2 release!
