### ISSUE TITLE
[Feature Request] resizable window

### ISSUE THREAD

**Issue by yet-another-average-joe** [Ghostkeeper/SettingsGuide#2]
Thanks ! Settings Guide is back !!!

But the window is not resizable under Windows 10. The mouse cursor changes when it goes over the borders, but the borders can't be grabbed...

(I don't remember with 3.6)

**Comment by Ghostkeeper** [comment]
I've actually implemented this! Mostly because I needed to resize it to test, and accidentally committed it [here](https://github.com/Ghostkeeper/SettingsGuide/commit/4de1257cdd35e14d1be18c9c499b56f59655a28e). It'll be released with the next version. In fact, I need to remember putting a minimum size on there because currently you can make it so small that things start to break a bit. Done that [now](https://github.com/Ghostkeeper/SettingsGuide/commit/786c4d8f4032e2cf394ad1cdad335036c5aff6b9).

In 3.6 it was also not resizable. So that's a new feature for version 1.3.
