### ISSUE TITLE
 2.5 & glossary.md 

### ISSUE THREAD

**Issue by 5axes** [Ghostkeeper/SettingsGuide#36]
Hello Ghostkeeper
This is not realy an issue but more a question concerning the translation of the glossary.md  new page.

- If we translate in a different langage the alphabetique order will not be preserved. Should we have to modify also the initial order ?
- I want to keep the term in English after translation. Is that ok for you?

**Comment by Ghostkeeper** [comment]
I think it's more useful to have the list in alphabetical order for whatever alphabet the language uses. You can re-order such that a French reader would find the term they need more quickly. No sense in keeping the English alphabetical order :smiley: 

Yeah keeping the English term is fine. The "rule" for this in Cura itself is that technical/industry terms should not be translated if the community commonly uses the English term. It's not a rule that is enforced rigidly (because there's no objective or automated way to really test whether terms are used in English or in French in the community) so usually either way is fine. And I think that goes for the Settings Guide too.
