### ISSUE TITLE
articles/experimental/support_tree_enable.md

### ISSUE THREAD

**Issue by 5axes** [Ghostkeeper/SettingsGuide#51]
`While tree support can be activated at the same time as ordinary support, this is generally not desirable.`

It's no longer the case since 4.8. Perhap's a modification can be made in the original text according to the Cura release ?

**Comment by Ghostkeeper** [comment]
No, this is intended. The Settings Guide supports Cura 4.0 through 4.9. And in each version of Cura it only shows the settings that exist in that version of Cura. Since `support_tree_enable` was removed in Cura 4.8, this text is no longer shown for Cura 4.8 and newer. For those versions, `support_structure.md` shows the corrected text (a setting that didn't exist yet in 4.7 and earlier).

So no modification depending on the version is necessary; the entire article is not even listed in Cura 4.8 and newer.
