### ISSUE TITLE
Settings Guide display issues with new Cura 4.9.1 on Macbook (with Intel processor) 

### ISSUE THREAD

**Issue by MDallasVoxel** [Ghostkeeper/SettingsGuide#55]
Hello, 

After upgrading my Cura to 4.9.1 from 4.8.0 my settings guide no longer displays correctly and seems to be too large for the allowable area. 
![Screen Shot 2021-06-09 at 3 45 16 PM](https://user-images.githubusercontent.com/85652369/121715376-a90ae980-ca93-11eb-8894-f9246e0c4c1c.PNG)
![Screen Shot 2021-06-10 at 3 00 21 PM](https://user-images.githubusercontent.com/85652369/121715379-a9a38000-ca93-11eb-9672-d7190c7d5a60.PNG)
I am running a Macbook Air running version 10.13.6.
Thanks M.

**Comment by Ghostkeeper** [comment]
Hmm, well you can still disable showing the guide in the tooltips, to go to the situation that it was in in Settings Guide 2.5. It's done by opening the guide the same way as before (Extensions -> Settings Guide -> Settings Guide) and then under the About category, on the page for Preferences, uncheck the "Show Articles in Tooltips" option, and then restart Cura.

The problem raised here is a bit of a difficult one to solve for everyone. The worst case for the tooltip going out of the window would require the width to be about equal to the original tooltip width. However that becomes pretty hard to read then, and almost always requires scrolling through the tooltips:
![image](https://user-images.githubusercontent.com/2448634/123497350-57cf2e00-d62d-11eb-9a35-13b970ffed88.png)

Going by the best case though, it seems the current implementation (tooltip gets widened by 2.5x the theme's default width) requires the window to be at least 1270 pixels wide. Cura's minimum is 1140 pixels, so there's a space of 130 pixels where part of it could get cut off even if the settings panel is all the way to the right.

So the question here is whether it's worth it to reduce readability for everyone, in order to support people with screens of less than 1280 pixels width. At the moment, [Tweakers](https://tweakers.net/laptops/vergelijken/) (Dutch tech website) lists 4 laptops out of 4.500 that have a screen resolution of 1280 pixels width, and none that are lower than that. Based on that data, I don't think it's worth it right now. Those users are better off disabling the feature to display the guide in tooltips.

Considering the difficulty that people seem to have to find the preferences, I think adding a preference for this width factor is not very user friendly either. It would be kind of an arbitrary number for an unsuspecting user, and too hidden for those who would actually need it.
