### ISSUE TITLE
Cura 5.x setting's search not working as it should when settingsGuide is installed

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ghostkeeper/SettingsGuide#93]
Cura 5,x, Wintel 10/64bit
SettingsGuied 2.9.0.

**What's the problem:**
When searching for specific setting Cura unfolds all catagories tabs showing all settings.

**What should have happened:**
Cura should return only the settings that includes the searched keyword.

**Solution / workaround:**
Uninstalling the plug for search to work as intended.

**Comment by Ghostkeeper** [comment]
I'm unable to reproduce this issue. For instance, this is the result when I search for the word "draft":
![image](https://user-images.githubusercontent.com/2448634/178157020-ffaf4642-01e5-4107-b091-9aec9ce4fb6b.png)

I use the search function all the time myself, and I always have the Settings Guide loaded.

The search results do change by the Settings Guide though, if showing the guide in the tooltips (which is default). That's because Cura searches through both the label and the tooltip of the setting when you search for a keyword. If the Settings Guide changes the tooltip, the search results will change. Because the Settings Guide has more text, generally you'll get more search results. But for the most part I think the search results are better. Especially for keywords like "stringing" which are in the Settings Guide but not in the tooltips.

Which keyword(s) are you using to search, that you can reproduce the problem with?

**Comment by Thisismydigitalself** [comment]
Hi there!
Searching "draft" returns the same results as with yours. 
Please try and search the keyword"flow".
When plug is install Cura unfolds ALL categories and shows lots of unrelated settings.
Without the plug, i get only the relevant settings:
![image](https://user-images.githubusercontent.com/30949968/178159676-5bea0793-e6fc-4db0-bb77-04cd7f352d1b.png)

Cheers.

**Comment by Ghostkeeper** [comment]
Hmm, no I still only get settings with the word "flow" in their articles.
![image](https://user-images.githubusercontent.com/2448634/178600662-aa37aa5c-fe0e-4c17-a8d3-1e7665e7071f.png)
Are you finding any results that don't mention "flow"?

Many articles refer to flow rate, because adjusting the speed, layer height or line width adjusts the rate at which material flows through the nozzle. So you'll get quite a few results. But still only a fraction of the total settings list.

**Comment by Thisismydigitalself** [comment]
Searching for "flow" and "retraction"
----------------------------------------

Results **_without_** the plug:

"Flow"

![ice_screenshot_20220713-084803](https://user-images.githubusercontent.com/30949968/178660593-f7265237-5824-4579-8e29-848abef95a35.png)

"retraction"

![ice_screenshot_20220713-084924](https://user-images.githubusercontent.com/30949968/178660594-8bb6f09f-ca49-470b-b9bb-055f28853f6d.png)

----------------------------------------
Results **_with plug installed_**:

"Flow"
(note how many more lines are hidden below and which i did not screenshot..)

![ice_screenshot_20220713-085151](https://user-images.githubusercontent.com/30949968/178660608-daa40d11-c209-487e-97ee-843114c0654a.png)

"retraction"

![ice_screenshot_20220713-085214](https://user-images.githubusercontent.com/30949968/178660609-e96ed268-66a6-49c2-a67c-4d412d7da692.png)

**Comment by Ghostkeeper** [comment]
Thanks, that looks correct then. All of the articles in your screenshot about flow mention the word "flow", and all of the articles in your screenshot about retraction mention the word "retraction" (or plural). Good to have that verified!

**Comment by 5axes** [comment]
You can keep the plugin et the search function. 
You just need in the option of the plugin to keep the  standard Help text , and not replace by the plugin text

**Comment by 5axes** [comment]
![image](https://user-images.githubusercontent.com/11015345/178774305-ed51f0b7-8425-4258-b89f-54ee2c1bb6f5.png)

**Comment by Thisismydigitalself** [comment]
@5axes 
You're the man! i did not know this even exists. and even if i did, the description does not even insinuate what it means.. 
Thank you. things looks much better now.

**Comment by 5axes** [comment]
@Ghostkeeper should write a new plugin the "**Plugin Guide for the Plugin Settings Guide**"  :)
